# Generated by Django 5.1.2 on 2024-11-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliographie', '0003_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='date_publication',
            field=models.IntegerField(),
        ),
    ]
